added error codes detection
neonlabsorg/neon-proxy.py pull request #155
Opened 2024-10-24 17:55 UTC by AnastasiyaTarasova

2024-10-29 14:07 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   59756 |      0     |      0.176 |    0.000986378 |         0.001 |
| getAccountInfo                    |   54711 |      0     |      0.12  |    0.0018296   |         0.001 |
| getBlocks                         |   24434 |      0     |      0.06  |    0.00071245  |         0.001 |
| getBlock                          |   16011 |      0     |      0.06  |    0.00178914  |         0.002 |
| getMultipleAccounts               |   13486 |      0     |      0.079 |    0.00233101  |         0.001 |
| getTransaction                    |   12393 |      0     |      0.241 |    0.011261    |         0.004 |
| getLatestBlockhash                |   10894 |      0     |      0.111 |    0.00165201  |         0.001 |
| getBlockTime                      |    5935 |      0     |      0.067 |    0.000653917 |         0     |
| sendTransaction                   |    5072 |      0     |      0.117 |    0.00880225  |         0.004 |
| getBalance                        |    1761 |      0     |      0.076 |    0.00158035  |         0.001 |
| getSignatureStatuses              |    1124 |      0     |      0.091 |    0.00192082  |         0.001 |
| getVersion                        |     601 |      0     |      0.048 |    0.00177704  |         0     |
| isBlockhashValid                  |     544 |      0     |      0.024 |    0.000516544 |         0     |
| simulateTransaction               |     491 |      0     |      0.006 |    0.00179633  |         0.001 |
| getSignaturesForAddress           |      61 |      0     |      0.016 |    0.00198361  |         0.002 |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.00084375  |         0.001 |
| getTokenAccountBalance            |      11 |      0     |      0.047 |    0.0125455   |         0.001 |
| getHealth                         |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0     |      0     |    0           |         0     |

</details>

2024-10-30 07:46 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   57583 |      0     |      0.272 |    0.0010456   |         0.001 |
| getAccountInfo                    |   54716 |      0     |      0.249 |    0.00211244  |         0.001 |
| getBlocks                         |   23816 |      0     |      0.147 |    0.000750924 |         0.001 |
| getBlock                          |   15618 |      0     |      0.065 |    0.00191747  |         0.002 |
| getMultipleAccounts               |   13415 |      0     |      0.184 |    0.00252449  |         0.001 |
| getTransaction                    |   12498 |      0     |      0.381 |    0.0129432   |         0.004 |
| getLatestBlockhash                |   10707 |      0     |      0.131 |    0.00192416  |         0.001 |
| getBlockTime                      |    6010 |      0     |      0.044 |    0.000723461 |         0     |
| sendTransaction                   |    5112 |      0     |      0.147 |    0.00956025  |         0.005 |
| getBalance                        |    1763 |      0     |      0.06  |    0.00242995  |         0.001 |
| getSignatureStatuses              |    1124 |      0     |      0.25  |    0.00236388  |         0.001 |
| getVersion                        |     602 |      0     |      0.104 |    0.00194186  |         0     |
| isBlockhashValid                  |     544 |      0     |      0.271 |    0.00102941  |         0     |
| simulateTransaction               |     491 |      0     |      0.036 |    0.0036945   |         0.003 |
| getSignaturesForAddress           |      61 |      0     |      0.003 |    0.00139344  |         0.001 |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00090625  |         0.001 |
| getTokenAccountBalance            |      12 |      0     |      0.068 |    0.006       |         0     |
| getHealth                         |       3 |      0     |      0.001 |    0.000666667 |         0.001 |
| getFirstAvailableBlock            |       2 |      0.001 |      0.001 |    0.001       |         0.001 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |         0.001 |

</details>

2024-10-30 09:50 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   63247 |      0     |      0.193 |    0.000914652 |        0.001  |
| getAccountInfo                    |   54810 |      0     |      0.114 |    0.00178486  |        0.001  |
| getBlocks                         |   26018 |      0     |      0.052 |    0.000715582 |        0.001  |
| getBlock                          |   16982 |      0     |      0.033 |    0.00174738  |        0.002  |
| getMultipleAccounts               |   13573 |      0     |      0.193 |    0.00212849  |        0.001  |
| getTransaction                    |   12540 |      0     |      0.118 |    0.00904258  |        0.004  |
| getLatestBlockhash                |   11310 |      0     |      0.09  |    0.00142732  |        0.001  |
| getBlockTime                      |    5876 |      0     |      0.051 |    0.000649421 |        0      |
| sendTransaction                   |    5126 |      0     |      0.33  |    0.00914768  |        0.004  |
| getBalance                        |    1764 |      0     |      0.06  |    0.00177268  |        0.001  |
| getSignatureStatuses              |    1124 |      0     |      0.036 |    0.00138256  |        0.001  |
| getVersion                        |     588 |      0     |      0.035 |    0.00142177  |        0      |
| isBlockhashValid                  |     544 |      0     |      0.024 |    0.000612132 |        0      |
| simulateTransaction               |     491 |      0     |      0.006 |    0.00194908  |        0.002  |
| getSignaturesForAddress           |      67 |      0     |      0.005 |    0.0021194   |        0.002  |
| requestAirdrop                    |      32 |      0     |      0.001 |    0.000875    |        0.001  |
| getTokenAccountBalance            |       5 |      0     |      0.024 |    0.0078      |        0.001  |
| getHealth                         |       4 |      0     |      0.001 |    0.0005      |        0.0005 |
| getFirstAvailableBlock            |       2 |      0     |      0.001 |    0.0005      |        0.0005 |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |        0.001  |
| getClusterNodes                   |       1 |      0     |      0     |    0           |        0      |

</details>

2024-11-20 18:41 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getAccountInfo                    |  496304 |      0     |      0.412 |    0.00253766  |         0.001 |
| getSlot                           |  226923 |      0     |      0.421 |    0.0015884   |         0.001 |
| getMultipleAccounts               |  108141 |      0     |      0.397 |    0.00337419  |         0.001 |
| getTransaction                    |  104730 |      0     |      0.342 |    0.00985564  |         0.006 |
| getBlocks                         |   98954 |      0     |      0.204 |    0.00106735  |         0.001 |
| getLatestBlockhash                |   55863 |      0     |      0.472 |    0.00380132  |         0.001 |
| sendTransaction                   |   52606 |      0     |      0.468 |    0.0133487   |         0.008 |
| getBlockTime                      |   52399 |      0     |      0.17  |    0.00102815  |         0     |
| getBlock                          |   50836 |      0     |      0.082 |    0.00223643  |         0.002 |
| getBalance                        |   15217 |      0     |      0.148 |    0.00263929  |         0.001 |
| getSignatureStatuses              |    1437 |      0     |      0.194 |    0.00295825  |         0.001 |
| getVersion                        |     741 |      0     |      0.167 |    0.00284345  |         0.001 |
| isBlockhashValid                  |     700 |      0     |      0.025 |    0.000937143 |         0     |
| simulateTransaction               |     491 |      0     |      0.004 |    0.00125662  |         0.001 |
| getSignaturesForAddress           |      63 |      0     |      0.019 |    0.00338095  |         0.002 |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00096875  |         0.001 |
| getHealth                         |       3 |      0.001 |      0.026 |    0.011       |         0.006 |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000666667 |         0.001 |
| getFirstAvailableBlock            |       2 |      0     |      0     |    0           |         0     |
| getMinimumBalanceForRentExemption |       1 |      0.001 |      0.001 |    0.001       |         0.001 |
| getClusterNodes                   |       1 |      0.004 |      0.004 |    0.004       |         0.004 |

</details>

2025-01-13 23:58 UTC, afalaleev requested changes

2025-01-13 23:58 UTC, afalaleev commented on common/neon/evm_log_decoder.py
> +    sol_inner_ix_idx: int | None
This structure isn't used.
Remove it.

2025-01-13 23:58 UTC, afalaleev commented on common/neon/transaction_decoder.py
> +
Remove this change

2025-01-13 23:58 UTC, afalaleev commented on common/neon/evm_log_decoder.py
> +        return NeonTxErrorLogInfo(
```
return cls(
    ...
)
```

2025-01-13 23:58 UTC, afalaleev commented on common/neon/evm_log_decoder.py
> +    def to_clean_copy(self, log: _NeonTxLogDraft) -> NeonTxErrorLogInfo:
The parameter `log` isn't used.
Remove it

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +                log_list.extend(log_info.log_msg_list())
Just replace this copy-paste with the call `evm_log_list = self._get_evm_log_list()`

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +            _tx_acct_key_list=None)
Replace this with the `fake_tx_ix = SolTxIxMetaInfo.default()`
Like in this line:
https://github.com/neonlabsorg/neon-proxy.py/blob/7a63b175fc74c30c2ec80f168f5861f5cec47444/proxy/executor/strategy_base.py#L377-L382

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +from common.utils.cached import cached_method, cached_property
`cached_property` isn't used

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +from common.solana.transaction_decoder import SolTxMetaInfo
`SolTxMetaInfo` isn't used.

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +)
The following types aren't used:
```
  SolRpcTxIxErrorInfo,
    SolRpcTxIxFieldErrorCode,
    SolRpcTxErrorInfo,
    SolRpcTxFieldErrorCode,
    SolRpcNodeUnhealthyErrorInfo,
    SolRpcTxReceiptInfo,
    SolRpcInvalidParamErrorInfo,
```

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +from common.neon.evm_log_decoder import SolTxIdx, NeonTxErrorLogInfo
`SolTxIdx` isn't used.

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +                tx_nonce = int.from_bytes(data[28:35])
what is the `data` here?

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +                req_gas_limit = int.from_bytes(log_recdata[32:64])
what is the `log_recdata` here?

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +from common.solana_rpc.transaction_list_sender import SolTxSendState
Please replace 5 lines above with the:
``` from ..transaction_list_sender import (
     SolTxListSender,
     SolTxListSigner,
     SolTxStatClient,
     SolWatchTxSession,
     SolTxSendState,
)
```

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +from ..solana.signature import SolTxSig
`SolTxSig` isn't used

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +from ..solana.transaction import SolTx
`SolTx` isn't used

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +from ..solana.transaction_meta import SolRpcTxSlotInfo, SolRpcTxReceiptInfo
`SolRpcTxSlotInfo` isn't used

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +    SolBlockhashNotFound,
`SolBlockhashNotFound` isn't used.

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +    SolCbExceededError,
`SolNoMoreRetriesError` isn't used.

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +        super().__init__(cfg, stat_client, sol_session, sol_tx_signer)
Surplus ctor, it doesn't do anything

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +        super().clear()
Surplus method

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +    def _add_tx_receipt(
This method - is just a copy-paste of the parent method

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +    def _decode_tx_status(self, tx: SolTx, now: int, tx_receipt: SolRpcTxReceiptInfo) -> _DecodeResult:
Not clear - why this method is copy-paste of the parent?

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/transaction_error_parser.py
> +    def _get_log_list(self) -> tuple[str, ...]:
For what?

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/transaction_list_sender.py
> +from common.neon.neon_tx_error_parser import NeonTxErrorParser
`from ..neon.neon_tx_error_parser`

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/transaction_list_sender.py
> +        neon_tx_error_parser = NeonTxErrorParser(tx, tx_receipt)
**Solana** Tx Sender shouldn't know about the `NeonTxErrorParser`

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +import dataclasses
`dataclasses` isn't used

2025-01-13 23:58 UTC, afalaleev commented on common/neon/neon_tx_error_parser.py
> +import re
Looks bad that this file is in the `neon/`
Because there are cross includes between 2 directories `solana_rpc` and `neon`

2025-01-13 23:58 UTC, afalaleev commented on common/solana_rpc/transaction_error_parser.py
> +        log_list = self._get_evm_log_list()
This method is a Neon error, not Solana

2025-01-13 23:58 UTC, afalaleev commented on requirements.txt
> +
For what?

2025-01-13 23:58 UTC, afalaleev commented on tests/solana/test_cb_exceeded.py
>  from common.solana_rpc.transaction_list_sender import SolTxListSender
`SolTxListSender` isn't used

2025-01-13 23:58 UTC, afalaleev commented on proxy/operator_resource/resource_manager.py
>  from common.solana_rpc.transaction_list_sender import SolTxListSender
`SolTxListSender` isn't used

2025-01-14 17:24 UTC, AnastasiyaTarasova commented on common/neon/neon_tx_error_parser.py
> +            _tx_acct_key_list=None)
replaced https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/2378a85dce5da8d221ea792efb0bb790b4c36f6f

2025-01-14 17:32 UTC, AnastasiyaTarasova commented on common/neon/evm_log_decoder.py
> +        return NeonTxErrorLogInfo(
done https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/f86851d1f6ccf155b35eb8e617a16e391aaa713a

2025-01-14 17:34 UTC, AnastasiyaTarasova commented on common/neon/evm_log_decoder.py
> +    sol_inner_ix_idx: int | None
removed https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/f8f4ab2a37ea671d5b96244f72dda5acbc0625df

2025-01-14 20:48 UTC, AnastasiyaTarasova commented on common/solana_rpc/transaction_error_parser.py
> +        log_list = self._get_evm_log_list()
moved

2025-01-14 21:32 UTC, AnastasiyaTarasova commented on common/neon/neon_tx_error_parser.py
> +                tx_nonce = int.from_bytes(data[28:35])
fixed https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/51e7853fa1b576e11592898216eed5ad8c6df1be

2025-01-14 21:41 UTC, AnastasiyaTarasova commented on common/solana_rpc/transaction_list_sender.py
> +from common.neon.neon_tx_error_parser import NeonTxErrorParser
done https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/637e5fd8f343b9e37e853e19d5929b22ad39352c

2025-01-14 21:51 UTC, AnastasiyaTarasova commented on common/neon/neon_tx_error_parser.py
> +from common.neon.evm_log_decoder import SolTxIdx, NeonTxErrorLogInfo
removed https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/f8f4ab2a37ea671d5b96244f72dda5acbc0625df

2025-01-16 21:07 UTC, AnastasiyaTarasova commented on common/neon/neon_tx_error_parser.py
> +import re
moved to solana_rpc https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/4b36c423c53496513e52e8e77875b5abf402a2a2

2025-01-16 21:19 UTC, AnastasiyaTarasova commented on common/solana_rpc/transaction_list_sender.py
> +        neon_tx_error_parser = NeonTxErrorParser(tx, tx_receipt)
fixed https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/f3e6944115db4f157649c2f51e11ffe93a5f93cd

2025-01-17 02:37 UTC, AnastasiyaTarasova commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +        super().__init__(cfg, stat_client, sol_session, sol_tx_signer)
removed https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/e6a5ade4a18fc7e8c190ab7d13fcd802b0902a1e

2025-01-17 02:37 UTC, AnastasiyaTarasova commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +        super().clear()
removed https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/e6a5ade4a18fc7e8c190ab7d13fcd802b0902a1e

2025-01-17 02:38 UTC, AnastasiyaTarasova commented on common/solana_rpc/neon_sol_tx_list_sender.py
> +    def _decode_tx_status(self, tx: SolTx, now: int, tx_receipt: SolRpcTxReceiptInfo) -> _DecodeResult:
separated the logic https://github.com/neonlabsorg/neon-proxy.py/pull/155/commits/2331d8425605e52dc036fd98edec75df66c4ad72

2025-01-21 04:00 UTC, AnastasiyaTarasova commented on common/neon/evm_log_decoder.py
> +    def to_clean_copy(self, log: _NeonTxLogDraft) -> NeonTxErrorLogInfo:
done

2025-01-21 05:34 UTC, AnastasiyaTarasova commented on common/neon/transaction_decoder.py
> +
done

2025-01-25 12:20 UTC, afalaleev commented
Close due to refactored PR https://github.com/neonlabsorg/neon-proxy.py/pull/229

2025-01-25 12:20 UTC, closed without merging