DOPS-664 add docker-compose file
neonlabsorg/neon-proxy.py pull request #91
Opened 2024-07-19 13:58 UTC by himaster

DOPS-664 add docker-compose file

2024-07-22 18:15 UTC, neonlabstech commented
<details><summary>Solana Requests Statistics</summary>



|                                   |   count |   min_time |   max_time |   average_time |   median_time |
|:----------------------------------|--------:|-----------:|-----------:|---------------:|--------------:|
| getSlot                           |   72922 |      0     |      0.129 |    0.000705274 |         0     |
| getAccountInfo                    |   54166 |      0     |      0.091 |    0.00131848  |         0     |
| getBlocks                         |   27860 |      0     |      0.09  |    0.000469526 |         0     |
| getTransaction                    |   23681 |      0     |      0.42  |    0.00340742  |         0.001 |
| sendTransaction                   |   21646 |      0     |      0.144 |    0.00361411  |         0.002 |
| getBlock                          |   13985 |      0     |      0.039 |    0.00085177  |         0.001 |
| getMultipleAccounts               |    9049 |      0     |      0.102 |    0.00208067  |         0.001 |
| getBlockTime                      |    5793 |      0     |      0.071 |    0.000612981 |         0     |
| getLatestBlockhash                |    4460 |      0     |      0.102 |    0.00194709  |         0.001 |
| getBalance                        |    1755 |      0     |      0.093 |    0.00132023  |         0     |
| getSignatureStatuses              |    1033 |      0     |      0.087 |    0.00109777  |         0     |
| getVersion                        |     538 |      0     |      0.025 |    0.000931227 |         0     |
| isBlockhashValid                  |     498 |      0     |      0.017 |    0.000481928 |         0     |
| getSignaturesForAddress           |     132 |      0     |      0.023 |    0.00225758  |         0.002 |
| simulateTransaction               |      41 |      0     |      0.001 |    0.000219512 |         0     |
| requestAirdrop                    |      32 |      0     |      0.002 |    0.00071875  |         0.001 |
| getHealth                         |       3 |      0     |      0     |    0           |         0     |
| getTokenAccountBalance            |       3 |      0     |      0.001 |    0.000333333 |         0     |
| getFirstAvailableBlock            |       2 |      0     |      0     |    0           |         0     |
| getMinimumBalanceForRentExemption |       1 |      0     |      0     |    0           |         0     |
| getClusterNodes                   |       1 |      0.001 |      0.001 |    0.001       |         0.001 |

</details>

2024-07-25 09:30 UTC, afalaleev reviewed
@himaster please rebase your PR, because there were changes in neon-tests image

2024-07-28 19:02 UTC, afalaleev requested changes

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      LOG_FULL_OBJECT_INFO: "YES"
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      CONFIG: custom
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      SLOT_PROCESSING_DELAY: 40
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      POSTGRES_TIMEOUT: 15
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      REINDEX_THREAD_COUNT: 5
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      START_SLOT: LATEST
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      REINDEX_START_SLOT: CONTINUE
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +    expose:
Please remove this section

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +    ports:
Please remove this section

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       LOG_FULL_OBJECT_INFO: "NO"
Please remove this setting

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       MIN_OPERATOR_BALANCE_TO_WARN: 4565760000 # = 913152000 * 5 (5 storage accounts) = 4.56576 SOL
Please remove this setting

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       MIN_OPERATOR_BALANCE_TO_ERR: 913152000 # = solana rent 131072 (= Rent-exempt minimum: 0.913152 SOL) SOLs to create a storage
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       MINIMAL_GAS_PRICE: 1
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       COMMIT_LEVEL: Confirmed
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       CU_PRIORITY_FEE: 2
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       SIMPLE_CU_PRIORITY_FEE: 1
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       DEBUG_CMD_LINE: "NO"
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       FUZZ_FAIL_PCT: 0
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       CONST_GAS_PRICE: 2
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       MINIMAL_WITHOUT_CHAIN_ID_GAS_PRICE: 1
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +       LOG_CLEF_FORMAT: "NO"
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      - 127.0.0.1:8889:8888
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on docker-compose.yml
> +      - "8888"
Please remove this variable

2024-07-28 19:02 UTC, afalaleev commented on .gitignore
> +indexer_db/
Not exist directory

2024-07-28 19:02 UTC, afalaleev commented on .gitignore
> +id.json
Not exist file

2024-07-28 20:18 UTC, afalaleev requested changes

2024-07-28 20:18 UTC, afalaleev commented on docker-compose.yml
> +       RUST_BACKTRACE: 0
Please remove this variable

2024-07-29 13:33 UTC, afalaleev approved these changes

2024-07-29 13:35 UTC, merged